name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: demo0310
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REGISTRY: ghcr.io
  IMAGE_TAG: ${{ github.sha }}
  AKS_CLUSTER: demo
  AKS_RESOURCE_GROUP: aks-demo-alb-rg
  AKS_NAMESPACE: demo0310
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  PATH_TO_K8S_MANIFEST: k8s/application.yaml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
            java-version: 17
            distribution: 'microsoft'

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Build Docker image
        run: docker build -t $DOCKER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure AKS Get Credentials
        run: az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER }}
       
      - name: Replace IMAGE_TAG in k8s/application.yaml
        run: sed -i "s/\$IMAGE_TAG/${{ env.IMAGE_TAG }}/g" k8s/application.yaml

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/application.yaml